<a href="https://colab.research.google.com/github/leonardolunamoreno/Computadoras-y-programaci-n2021-grupo-1157/blob/main/03NumpyOperaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
n1 = np.array([[1,2,3],
              [10,11,12],
              [-5,-8,-14]])
n1
print(n1)
print(n1.shape)

[[  1   2   3]
 [ 10  11  12]
 [ -5  -8 -14]]
(3, 3)


In [ ]:
# Las operaciones aritmeticas se aplican a todos ls elementos de la matriz 
n1 * 200

array([[  200,   400,   600],
       [ 2000,  2200,  2400],
       [-1000, -1600, -2800]])

In [ ]:
# Aplicar la operación a un elemento 
n1[1] + 15 # En este caso la primer columna se suman 15 a todos los elementos 

array([25, 26, 27])

In [ ]:
n1 / 5.45 

array([[ 0.18348624,  0.36697248,  0.55045872],
       [ 1.83486239,  2.01834862,  2.20183486],
       [-0.91743119, -1.46788991, -2.56880734]])

In [ ]:
# Usar operadores lógicos por broadcasting 
n1 > 1 # Compara cada uno de los elementos contra la operación aquí descrita

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
n2 = np.array([1,2,3])
n3 = np.array([[2],[4],[3]]) 
print(n2)
print(n2.shape)

print(n3)
print(n3.shape)

print(n1)
print(n1.shape)

[1 2 3]
(3,)
[[2]
 [4]
 [3]]
(3, 1)
[[  1   2   3]
 [ 10  11  12]
 [ -5  -8 -14]]
(3, 3)


In [ ]:
n1 * n2 # Operaciones de matrices 

array([[  1,   4,   9],
       [ 10,  22,  36],
       [ -5, -16, -42]])

In [ ]:
n1 / n3 # Más operaciones de matrices 

array([[ 0.5       ,  1.        ,  1.5       ],
       [ 2.5       ,  2.75      ,  3.        ],
       [-1.66666667, -2.66666667, -4.66666667]])

In [ ]:
n4 = n1 + 20 
n4 

array([[21, 22, 23],
       [30, 31, 32],
       [15, 12,  6]])

In [ ]:
n1 * n4 # Aqui se multiplican todos los elementos de cada matriz 

array([[ 21,  44,  69],
       [300, 341, 384],
       [-75, -96, -84]])

In [ ]:
# Generar arreglos con valores aleatorios
np.random.rand(2,2,2)  
# si se quieren guardar los valores random, tenemos que asignarlos a una variable

array([[[0.4424985 , 0.79086989],
        [0.93644581, 0.84594888]],

       [[0.33024059, 0.39672568],
        [0.09180989, 0.98681613]]])

In [ ]:
# randit genera valores aleatrois entre un rango 
np.random.randint(1,4,(2,2,2)) # Estamos usando el paquete " random " de numpy 

array([[[3, 3],
        [2, 1]],

       [[1, 1],
        [2, 1]]])

array([[[1, 1],
        [1, 1]],

       [[1, 3],
        [2, 3]]])

In [ ]:
np.random.randint(8,256,(3,2,4))

array([[[246, 214, 202, 142],
        [ 59, 221,  17, 175]],

       [[ 38, 183, 255,  31],
        [ 48, 122,  80,  92]],

       [[112, 184,  77, 224],
        [152, 189,  10, 142]]])

In [ ]:
numeros = np.array([[2.43, -3, 48.9999, -5.61],
                   [np.inf, -np.inf, np.inf, np.inf],
                   [np.nan, 17.78, 12, 22]])
numeros

array([[ 2.43  , -3.    , 48.9999, -5.61  ],
       [    inf,    -inf,     inf,     inf],
       [    nan, 17.78  , 12.    , 22.    ]])

In [ ]:
# Funciones de valor
print(np.abs(numeros))
print(np.floor(numeros))
print(np.ceil(numeros))
print(np.round(numeros))

[[ 2.43    3.     48.9999  5.61  ]
 [    inf     inf     inf     inf]
 [    nan 17.78   12.     22.    ]]
[[  2.  -3.  48.  -6.]
 [ inf -inf  inf  inf]
 [ nan  17.  12.  22.]]
[[  3.  -3.  49.  -5.]
 [ inf -inf  inf  inf]
 [ nan  18.  12.  22.]]
[[  2.  -3.  49.  -6.]
 [ inf -inf  inf  inf]
 [ nan  18.  12.  22.]]


## Funciones de valor
* ```np.abs()```
* ```np.around()```
* ```np.ceil()```
* ```np.exp()```
* ```np.exp2()```
* ```np.fabs()```
* ```np.fix()```
* ```np.floor()```
* ```np.log()```
* ```np.log10()```
* ```np.log1p()```
* ```np.log2()```
* ```np.logaddexp()```
* ```np.logaddexp2()```
* ```np.round()```


In [ ]:
# Funciones de evaluación de arreglos
print(np.isfinite(numeros)) #segun esto no se puede correr debido a la configuracion
print(np.isnan(numeros)) # Es similiar al " null "
print(np.isreal(numeros))
print(np.isscalar(numeros))

[[ True  True  True  True]
 [False False False False]
 [False  True  True  True]]
[[False False False False]
 [False False False False]
 [ True False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
False


## Funciones estadísticas.

* ```np.amax()```
* ```np amin()```
* ```np.argmax()```
* ```np.argmin()```
* ```np.average()```
* ```np.correlate()```
* ```np.corrcoef()```
* ```np.count_nonzero()```
* ```np.cov()```
* ```np.cumprod()```
* ```np.cumsum()```
* ```np.histogram()```
* ```np.histogram2d()```
* ```np.histogram_bin_edges()```
* ```np.histogramdd()```
* ```np.max()```
* ```np.mean()```
* ```np.median()```
* ```np.min()```
* ```np.nanargmax()```
* ```np.nanargmin()```
* ```np.nancumprod()```
* ```np.nancumsum()```
* ```np.nanmax()```
* ```np.nanmean()```
* ```np.nanmedian()```
* ```np.nanmin()```
* ```np.nanpercentile()```
* ```np.nanquantile()```
* ```np.nanstd()```
* ```np.nansum()```
* ```np.nanvar()```
* ```np.percentile()```
* ```np.quantile()```
* ```np.std()```
* ```np.var()```



In [ ]:
# Funciones estadisticas 
numeros = np.random.randint(8,256,(3,2,4))
numeros

array([[[ 53, 148,  30, 124],
        [ 97, 247, 189, 201]],

       [[181, 219,   9, 102],
        [186, 129,  83, 163]],

       [[200,  30,  27, 135],
        [187, 193, 212,  64]]])

In [ ]:
print(np.max(numeros))
print(np.mean(numeros))
print(np.min(numeros))

247
133.70833333333334
9


In [ ]:
print(np.nanmax(numeros))
print(np.nanmin(numeros))
print(np.nanmean(numeros))
print(np.nanmedian(numeros))

247
9
133.70833333333334
141.5


In [ ]:
np.histogram(numeros)

(array([4, 1, 1, 3, 1, 3, 1, 5, 4, 1]),
 array([  9. ,  32.8,  56.6,  80.4, 104.2, 128. , 151.8, 175.6, 199.4,
        223.2, 247. ]))

## Funciones de valor
* ```np.abs()```
* ```np.around()```
* ```np.ceil()```
* ```np.exp()```
* ```np.exp2()```
* ```np.fabs()```
* ```np.fix()```
* ```np.floor()```
* ```np.log()```
* ```np.log10()```
* ```np.log1p()```
* ```np.log2()```
* ```np.logaddexp()```
* ```np.logaddexp2()```
* ```np.round()```


In [ ]:
# Copia y ordenamiento 
numeros1 = numeros # Alias de un arreglo determinado 
numeros1 = np.copy(numeros) # Copia del arreglo numeros 
numeros1 

array([[[ 53, 148,  30, 124],
        [ 97, 247, 189, 201]],

       [[181, 219,   9, 102],
        [186, 129,  83, 163]],

       [[200,  30,  27, 135],
        [187, 193, 212,  64]]])

In [ ]:
numeros1.sort()
numeros1

array([[[ 30,  53, 124, 148],
        [ 97, 189, 201, 247]],

       [[  9, 102, 181, 219],
        [ 83, 129, 163, 186]],

       [[ 27,  30, 135, 200],
        [ 64, 187, 193, 212]]])

In [ ]:
numeros1.sort(axis=2) # Con estas lineas se pueden ordenar los elementos de una columna en partícular
numeros1

array([[[ 30,  53, 124, 148],
        [ 97, 189, 201, 247]],

       [[  9, 102, 181, 219],
        [ 83, 129, 163, 186]],

       [[ 27,  30, 135, 200],
        [ 64, 187, 193, 212]]])

In [ ]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])
print(a)
print(b)
print(np.add(a,b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]


In [ ]:
# Raíz cuadrada 
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
c = b <= 4
c 

array([[ True,  True,  True],
       [ True, False, False]])